import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NotificationWrapper from "./_wrapper/notification-wrapper";
import { SessionProvider } from "next-auth/react";
import ApplicationWrapper from "./_wrapper/application-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + "bg-background-light  dark:bg-background-dark dark:text-text-dark"}>
        <ApplicationWrapper>
          <SessionProvider>
            {children}
            <NotificationWrapper />
          </SessionProvider>
        </ApplicationWrapper>
      </body>
    </html>
  );
}
